version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      commands: 
        - run: echo "build project"
        - run: npm install
        - run: npm run build
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test